[package]
name = "fenban"
version = "0.1.0"
edition = "2024"

[dependencies]
calamine = "0.31"
rand = "0.9"
serde = { version = "1.0", features = ["derive"] }
rayon = "1.11"
num_cpus = "1.17"

[dev-dependencies]
rand_distr = "0.5"
