[package]
name = "fenban"
version = "0.1.0"
edition = "2024"

[dependencies]
calamine = "0.24"
rand = "0.8"
rand_distr = "0.4"
serde = { version = "1.0", features = ["derive"] }
rayon = "1.10"
num_cpus = "1.16"
