[package]
name = "fenban"
version = "0.1.0"
edition = "2024"

[dependencies]
calamine = "0.31"
num_cpus = "1.17"
rand = "0.9"
rayon = "1.11"
rust_xlsxwriter = "0.91"
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
rand_distr = "0.5"
