[application]
name = "FenBan"

[bundle]
identifier = "com.tangxiangong.fenban.app"
publisher = "tangxiangong"
icon = [
    "icons/icon.icns",
    "icons/32x32.png",
    "icons/128x128.png",
    "icons/128x128@2x.png",
]
copyright = "Copyright (c) 2025 tangxiangong"
category = "Productivity"
short_description = "分班助手"

[bundle.macos]
license = "LICENSE-MIT"

[bundle.windows]
license = "LICENSE-MIT"
icon = ["icons/icon.ico"]
[bundle.windows.webview_install_mode.DownloadBootstrapper]
silent = true
